# get all persons
GET http://localhost:3000/api/persons

###

# get one person
GET http://localhost:3000/api/persons/644a180df3bf6a9476eb95cb

###

# delete a person
DELETE http://localhost:3000/api/persons/644a180df3bf6a9476eb95cb

###

# add a person
POST http://localhost:3000/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Mary Poppendeick",
    "number": "39-23-6423122"
}

###

# change a person
PUT http://localhost:3000/api/persons/644a180df3bf6a9476eb95cb HTTP/1.1
content-type: application/json

{
    "name": "Mary Poppendeick",
    "number": "23-31-43565499"
}